In [1]:
x=[i for i in range(1,11)]
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [5]:
import numpy as np
a=[1,2,3]
arr=np.array(a)
print(type(arr))
print(arr)
print(arr.ndim)

<class 'numpy.ndarray'>
[1 2 3]
1


In [7]:
arr=np.array(12)
print(arr.ndim)    #no dimension

0


In [8]:
import numpy as np
a=[[1,2],[3,4]]
arr=np.array(a)
print(arr.ndim)
print(arr.shape)

2
(2, 2)


In [16]:
import numpy as np
a=[1,2,3,4,5]
# arr=np.array(a)
arr=np.array(a,ndmin=5)
print(arr.ndim)
print(arr)
print(arr[0][0][0][0][4])

5
[[[[[1 2 3 4 5]]]]]
5


In [23]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr=np.array(a)
print(arr.ndim)
print(arr)
print(arr[1][4])

2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10


In [24]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.ndim)
print(arr)
print(arr[0][1][2])     #3rd element of 2nd array of the 1st array

3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [9]:
import numpy as np
a=np.array([1,2,3,4],ndmin=10)
print(a)
print(a.ndim)      #ndim is number of dimensions
print(a.shape)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
(1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


In [6]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a.ndim)      #ndim is number of dimensions
print(a.shape)

3
(1, 2, 2)


In [11]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.ndim)
print(arr)
newarr=arr.reshape(4,3)
print(newarr.ndim)
print(newarr)

1
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr.ndim)
print(arr)
newarr=arr.reshape(1,1,1,1,1,1,1,1,1,6)
print(newarr.ndim)
print(newarr)

1
[1 2 3 4 5 6]
10
[[[[[[[[[[1 2 3 4 5 6]]]]]]]]]]


In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.ndim)
print(arr)
newarr=arr.reshape(2,2,-1)
print(newarr.ndim)
print(newarr)

1
[1 2 3 4 5 6 7 8]
3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr)
newarr=arr.reshape(-1)
print(newarr.ndim)
print(newarr)

2
[[1 2 3]
 [4 5 6]]
1
[1 2 3 4 5 6]


In [17]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.ndim)
print(arr)
newarr=arr.reshape(-2)
print(newarr.ndim)
print(newarr)
newarr1=newarr.reshape(3,-1)
print(newarr1.ndim)
print(newarr1)

2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
[1 2 3 4 5 6 7 8 9]
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
a=np.array([1,2,3])
for x in a:
    print(x)

1
2
3


In [21]:
a=np.array([[1,2],[3,4]])
for x in a:
    for y in x:
        print(y)

1
2
3
4


In [22]:
a=np.array([[1,2],[3,4]])
for x in np.nditer(a):    #nditer means number of iterationsjmn
    print(x)

1
2
3
4
